import pandas as pd
import numpy as np

class FeatureEngineer:
    def __init__(self, date_column="date", target_column="demand"):
        self.date_col = date_column
        self.target_col = target_column

    def generate_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Organically reduces forecasting error by generating rich time-series features.
        """
        df = df.copy()
        df[self.date_col] = pd.to_datetime(df[self.date_col])
        df = df.sort_values(self.date_col).reset_index(drop=True)

        # Time-based encodings
        df['day_of_week'] = df[self.date_col].dt.dayofweek
        df['month'] = df[self.date_col].dt.month
        df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)

        # Lag features
        for lag in [1, 7, 14]:
            df[f'lag_{lag}'] = df[self.target_col].shift(lag)

        # Rolling statistics
        df['rolling_mean_7'] = df[self.target_col].shift(1).rolling(window=7).mean()
        df['rolling_std_7'] = df[self.target_col].shift(1).rolling(window=7).std()

        # Drop NaNs generated by shifting and rolling
        df = df.dropna().reset_index(drop=True)
        return df
